### PR TITLE
MNT: Remove deprecated gfit and nmpfit

### LINKED ISSUE #87: remove nmpfit in v 3.4.14
It was deprecated in 3.4.13. Confirm that there is a release of stistools which does not use nmpfit.

### PR DESCRIPTION
**Pull request by pllim**
Fix #87 

xref spacetelescope/stistools#37

### CODE REVIEW

**Comment by nden** [comment]
`nmpfit` cannot be removed before mktrace is replaced with astropy.modeling.

**Comment by pllim** [comment]
That is unfortunate. @nden , what can I do to move this forward?

**Comment by nden** [comment]
@pllim As I said spacetelescope/stistools#37 needs to be resolved first. At the time it was waiting on reworking the regression tests. I'm not sure what the current situation is.

**Comment by pllim** [comment]
I'll resolve conflict when this gets an okay to move ahead.

**Comment by pllim** [comment]
This now has conflicts and I lost interest to work on it. So I am closing this PR.

**Pull request closed without merging**
