### PR TITLE
remove deprecated fits calls

### PR DESCRIPTION
**Pull request by nden**
@stsci-hack Please review

### CODE REVIEW

**Comment by pllim** [comment]
That's what I did with Pysynphot, so :+1: from me FWIW.

**Comment by pllim** [comment]
Note: After this is merge, we should do a release and update AstroConda with the new release.

**Comment by jhunkeler** [comment]
@pllim If these changes still work under Astropy 1.2.1, then I don't see why we couldn't.

**Comment by pllim** [comment]
They should already work with Astropy 1.2.

**Comment by nden** [comment]
Please don't do a release before someone checks the drizzlepac tests.

**Comment by jhunkeler** [comment]
@nden Speaking of that... 50% of the drizzlepac tests are failing in dev right now because of the deprecated FITS calls.

**Comment by nden** [comment]
Well, yes, that's how I tracked this one and the one in fitsblender. Some of the failures come from astropy but I fixed and merged that today. It should be available tomorrow. There might be deprecated calls in the rest of the dependencies and I am not familiar with those.

**Comment by pllim** [comment]
Maybe @mcara knows...

**Comment by nden** [comment]
Oh, and @jhunkeler all those failing tests are probably due to two calls.

**Comment by mcara** [comment]
I just made a PR to @nden branch https://github.com/nden/stsci.tools/pull/1to add one more fix that should solve a failing WFPC2 test.

**Comment by pllim** [comment]
So, can we merge this now?

**Comment by pllim** [comment]
Ops, @nden. I forgot about this one and merged #18. I'll manually fold in your remaining change in master.

**Pull request closed without merging**
