### PR TITLE
stpyfits: Apply possible solution for astropy 3.2

### LINKED ISSUE #98: stpyfits incompatible with Astropy 3.2
This is most probably caused by astropy/astropy#8502 . In `stpyfits`, it inherits `_ImageBaseHDU` and then assumes the header has a `copy()` method, which is no longer true.

https://github.com/spacetelescope/stsci.tools/blob/b926e11b4f1afa09fe7cf6b7893ebf2a54182c94/lib/stsci/tools/stpyfits.py#L69-L82

I think the fix here is to force the header to not lazy load (diligent load?) first before doing the copy.

Example failure log: https://travis-ci.org/spacetelescope/stsci.tools/jobs/543835788

### PR DESCRIPTION
**Pull request by jhunkeler**
... and discuss new failures.

EDIT: Fix #98

### CODE REVIEW

**Comment by pllim** [comment]
According to Simon, it is more like this:

https://github.com/astropy/astropy/blob/368dc06d11982cf525d71f8df394cb4c79f77182/astropy/io/fits/hdu/base.py#L150

**Comment by stsci-hack** [comment]
This seems to resolve the exceptions which stem from io.fits interface changes.  Unfortunately, the pytest  tests for stpyfits still all fail when run with astropy 3.2.  

```
============================= test session starts ==============================
platform linux -- Python 3.6.6, pytest-3.8.0, py-1.6.0, pluggy-0.7.1
rootdir: /user/hack/dev/release/stsci_python/pypi/stsci.tools/git/stsci.tools, inifile: setup.cfg
plugins: xdist-1.26.1, remotedata-0.3.0, openfiles-0.3.0, forked-1.0.2, doctestplus-0.1.3, arraydiff-0.2, ci-watson-0.1.2.dev11+g8f91a11f
collected 20 items

test_stpyfits.py FFFFFFFFF.FFFFFF..F.

=================================== FAILURES ===================================
_______________ TestStpyfitsFunctions.test_InfoConvienceFunction _______________
>       assert stpyfits.info(self.data('o4sp040b0_raw.fits'), output=False) == ans1
E       AssertionError: assert [(0, 'PRIMARY...(), ...), ...] == [(0, 'PRIMARY'...4), ...), ...]
E         At index 2 diff: (2, 'ERR', 1, 'ImageHDU', 71, (), '', '') != (2, 'ERR', 1, 'ImageHDU', 71, (62, 44), 'int16', '')
E         Use -v to get the full diff

```
It now looks to be the case that these DelayedHeaders need to be fully interpreted so that stpyfits can revise them to return the correctly expanded arrays.

**Comment by pllim** [comment]
@stsci-hack , I think Joe has an updated code but has not pushed it out yet. AFAIK, this is still WIP.

**Comment by pllim** [comment]
Superseded by #101

**Pull request closed without merging**
