### PR TITLE
Fix crash in TEAL when loading MDRIZTAB parameters

### PR DESCRIPTION
**Pull request by mcara**
Fixes a crash in TEAL when user attempts to load `MDRIZTAB` parameters in `astrodrizzle` but the `*_mdz.fits` file does not exist.

### CODE REVIEW

**Comment by pllim** [comment]
Wait, what? How does removing `relic` as a submodule fix this? @jhunkeler ?

**Comment by mcara** [comment]
@pllim "fix this" - I assume the issue of the crash when attempting to report an error. The fix is not in removing `relic` (which, IMO should not be part of _this_ package) but in replacing `ex.message` with `ex.args[0]`.

**Comment by pllim** [comment]
`relic` was a submodule. Having it as a submodule means you don't need to get it anew via `git` every time. I don't think removing it was necessary.

**Comment by mcara** [comment]
I am not sure I understand this. For example, I do not make `imagestats` a submodule of the `drizzlepac` so as to minimize download, or should I? I have noticed this because `git` was showing that `relic` was modified (well, it updated itself from its own repo and so it became modified compared to the submodule). Is this the recommended way? @jhunkeler

**Comment by pllim** [comment]
`relic` would be a non-issue if we move to use https://pypi.org/project/setuptools-scm/

**Pull request merged**
