### PR TITLE
Remove defunct modules

### LINKED ISSUE #73: Get rid of defunct tester tools
I want to delete these from the repo. Any objections?

* lib/stsci/tools/tester.py
* lib/stsci/tools/testutil.py

### LINKED ISSUE #74: Get rid of stash.py
When I open up `stash.py`, I see:

*This is a tool for stashing certain information used by the continuous integration system at STScI.  It is not intended for, or even expected to work, in any other application.*

What is this??? If pandokia does not use this, let's get rid of this.

### LINKED ISSUE #81: Update the help
Tyler Desjardins mentions that we should consider moving emails from `help[at]stsci.edu` to point to the web portal where possible and appropriate. For HST (or any non-JWST), it is https://hsthelp.stsci.edu . For JWST, it is https://jwsthelp.stsci.edu . Please update info in `setup.py`, `setup.cfg`, documentation, etc as appropriate. 

Please close this issue if it is irrelevant to your repository. This is an automated issue. *If this is opened in error, please let pllim know!* 

xref spacetelescope/hstcal#317

### PR DESCRIPTION
**Pull request by pllim**
* Fix #73 
* Fix #74 
* Fix #81 (except `author_email` in `setup.py`)
* Update license from STScI template, so it shows up properly on GitHub repo status bar.

### CODE REVIEW

**Comment by pllim** [comment]
Rebased and tests passed. Awaiting your response regarding #81.

**Comment by jhunkeler** [comment]
https://github.com/spacetelescope/jwst/blob/8d5757909d9b3ea42d9270f429aa2aff9c1fa60a/jwst/fits_generator/main.py#L373-L375
(99% irrelevant because I doubt this "test" is ever called, but it is there none the less...)

**Comment by pllim** [comment]
```python
def test(*args, **kwds):
    from stsci.tools import tester
    return tester.test(modname=__name__, *args, **kwds)
```

That should be rewritten on the `jwst` anyway. And since it is buried in `main.py`, it is probably not picked up by CI.

**Comment by pllim** [comment]
@nden , please re-review.

**Pull request merged**
