### PR TITLE
Setuptools conversion

### PR DESCRIPTION
**Pull request by jhunkeler**
- `python setup.py sdist` produces a usable tarball
- References to `d2to1` have been purged
- References to `stsci.distutils` have been purged
- All installation helper scripts have been purged
- "Tests pass"

### CODE REVIEW

**Comment by mcara** [comment]
We have to plan for a birthday party 🎉  for this PR...

**Comment by jhunkeler** [comment]
🎂 🎈 indeed

**Comment by pllim** [comment]
This PR is almost 2! 😉  (and has conflicts)

**Comment by jhunkeler** [comment]
🤷‍♂️ 
🎈 🎂 🎈

**Comment by pllim** [comment]
p.s. You can merge this whenever you want. I don't see any reason not to and you would know whether it breaks any builds better than I do.

**Comment by mcara** [comment]
Man, this baby is 2 years old. 🎂

**Comment by jhunkeler** [comment]
🍰

**Pull request merged**
